# Generated by Django 4.1.4 on 2022-12-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
