# Generated by Django 4.1.4 on 2022-12-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='adress',
            new_name='address',
        ),
    ]
