# Generated by Django 4.1.4 on 2022-12-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_users_location_users_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.IntegerField(null=True),
        ),
    ]
