# Generated by Django 4.1.4 on 2022-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ads_description_alter_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
