# Generated by Django 4.1.4 on 2023-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('moderator', 'moderator'), ('admin', 'admin')], max_length=200),
        ),
    ]
