# Generated by Django 4.1.4 on 2023-01-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='items',
            field=models.ManyToManyField(to='ads.ads'),
        ),
    ]
