# Generated by Django 4.1.4 on 2022-12-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_remove_user_location_user_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
