# Generated by Django 4.1.4 on 2022-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.ManyToManyField(to='ads.location'),
        ),
    ]
