# Generated by Django 4.1.4 on 2022-12-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_ads_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='location',
        ),
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.ManyToManyField(null=True, to='ads.location'),
        ),
    ]
